MIN_LENGTH = 5
MAX_LENGTH = 7
INWARD_LENGTH = 3
SPACE_POSITION = -4
INwWARD_PATTERN = r"^\d[ABD-HJLNP-UW-Z]{2}$"
OUTWARD_PATTERN = r"^[A-PR-UWYZ]"
INVALID_LETTERS_TO_INWARD = "CIKMOV"
INVALID_LETTERS_TO_FIRST_DIGIT = "QVX"
